### ISSUE TITLE
Add-on broken again

### ISSUE THREAD

**Issue by danamag** [kianjomi/RARBG-TorrentAPI-Stremio#4] opened 2019-05-25 07:57 UTC
This add-on hasn't been working for at least a few days (maybe even more then a week)

If i go to Board, i get:

```
Access to fetch at 'https://add-on.rarbg-torrentapi-stremio.xyz/catalog/other/local.json' from origin 'http://app.strem.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

All stream requests take a very long time and end with a failed `503` http status code.

If i put the same link to get streams in the browser, i get empty `infoHash` responses.

Example:
https://add-on.rarbg-torrentapi-stremio.xyz/stream/movie/tt6823368.json

Shows:
```
{
   "type":"movie",
   "id":"tt6823368",
   "streams":[
      {
         "availability":"1",
         "name":"RARBG",
         "title":" ,  S \/  L , 0 MB",
         "infoHash":null
      },
      {
         "availability":"1",
         "name":"RARBG",
         "title":" ,  S \/  L , 0 MB",
         "infoHash":null
      },
      {
         "availability":"1",
         "name":"RARBG",
         "title":" ,  S \/  L , 0 MB",
         "infoHash":null
      },
      {
         "availability":"1",
         "name":"RARBG",
         "title":" ,  S \/  L , 0 MB",
         "infoHash":null
      },
      {
         "availability":"1",
         "name":"RARBG",
         "title":" ,  S \/  L , 0 MB",
         "infoHash":null
      },
      {
         "availability":"1",
         "name":"RARBG",
         "title":" ,  S \/  L , 0 MB",
         "infoHash":null
      },
      {
         "availability":"1",
         "name":"RARBG",
         "title":" ,  S \/  L , 0 MB",
         "infoHash":null
      },
      {
         "availability":"1",
         "name":"RARBG",
         "title":" ,  S \/  L , 0 MB",
         "infoHash":null
      },
      {
         "availability":"1",
         "name":"RARBG",
         "title":" ,  S \/  L , 0 MB",
         "infoHash":null
      },
      {
         "availability":"1",
         "name":"RARBG",
         "title":" ,  S \/  L , 0 MB",
         "infoHash":null
      }
   ]
}
```

**Comment by sleeyax** [comment] 2019-06-03 15:06
The first error is caused by a missing CORS header on the test addons end, which can be fixed by adding an access control header - in PHP that would be something like ` header("Access-Control-Allow-Origin: *");` 

Secondly, I guess Stremio returns a `503 service unavailable` because of the slow response time of the server.

Thirdly, what's mainly causing the issue here is that this addon relies on the RARBG torrent API, which seems to be down for the moment. https://torrentapi.org/  and https://torrentapi.org/apidocs_v2.txt both return a `403 Forbidden` on my end.  It's possible this addon will automatically start working again when the API is fixed.

**Closed** 2019-06-04 16:39 UTC
